inspire_themes_anchors = {
  "Addresses": "http://inspire.ec.europa.eu/theme/ad", 
  "Administrative units": "http://inspire.ec.europa.eu/theme/au", 
  "Agricultural and aquaculture facilities": "http://inspire.ec.europa.eu/theme/af", 
  "Area management/restriction/regulation zones and reporting units": "http://inspire.ec.europa.eu/theme/am", 
  "Atmospheric conditions": "http://inspire.ec.europa.eu/theme/ac", 
  "Bio-geographical regions": "http://inspire.ec.europa.eu/theme/br", 
  "Buildings": "http://inspire.ec.europa.eu/theme/bu", 
  "Cadastral parcels": "http://inspire.ec.europa.eu/theme/cp", 
  "Coordinate reference systems": "http://inspire.ec.europa.eu/theme/rs", 
  "Elevation": "http://inspire.ec.europa.eu/theme/el", 
  "Energy resources": "http://inspire.ec.europa.eu/theme/er", 
  "Environmental monitoring facilities": "http://inspire.ec.europa.eu/theme/ef", 
  "Geographical grid systems": "http://inspire.ec.europa.eu/theme/gg", 
  "Geographical names": "http://inspire.ec.europa.eu/theme/gn", 
  "Geology": "http://inspire.ec.europa.eu/theme/ge", 
  "Habitats and biotopes": "http://inspire.ec.europa.eu/theme/hb", 
  "Human health and safety": "http://inspire.ec.europa.eu/theme/hh", 
  "Hydrography": "http://inspire.ec.europa.eu/theme/hy", 
  "Land cover": "http://inspire.ec.europa.eu/theme/lc", 
  "Land use": "http://inspire.ec.europa.eu/theme/lu", 
  "Meteorological geographical features": "http://inspire.ec.europa.eu/theme/mf", 
  "Mineral resources": "http://inspire.ec.europa.eu/theme/mr", 
  "Natural risk zones": "http://inspire.ec.europa.eu/theme/nz", 
  "Oceanographic geographical features": "http://inspire.ec.europa.eu/theme/of", 
  "Orthoimagery": "http://inspire.ec.europa.eu/theme/oi", 
  "Population distribution — demography": "http://inspire.ec.europa.eu/theme/pd", 
  "Production and industrial facilities": "http://inspire.ec.europa.eu/theme/pf", 
  "Protected sites": "http://inspire.ec.europa.eu/theme/ps", 
  "Sea regions": "http://inspire.ec.europa.eu/theme/sr", 
  "Soil": "http://inspire.ec.europa.eu/theme/so", 
  "Species distribution": "http://inspire.ec.europa.eu/theme/sd", 
  "Statistical units": "http://inspire.ec.europa.eu/theme/su", 
  "Transport networks": "http://inspire.ec.europa.eu/theme/tn", 
  "Utility and governmental services": "http://inspire.ec.europa.eu/theme/us"
}